spring:
  application:
    name: master
server:
  port: 8888
  servlet:
    context-path: /
    session:
      timeout: 1800
database:
  type: mysql
  url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
  driver: com.mysql.cj.jdbc.Driver
  user: root
  passwd: yxl12345
  InitialSize: 5
  minIdle: 5
  maxActive: 100